### ISSUE TITLE
Logged Out User able to navigate Application by Browser Event (Back Button)

### ISSUE THREAD

**Issue by ag02631** [openanthem/nimbus-core#513]
# Issue Details

**Type of Issue**  (check one with "X")
```
[X ] Bug Report => Please search GitHub for a similar issue or PR before submitting
[ ] Feature Request => Please ensure feature is not already in progress
[ ] Support Request => Please do not submit support requests here, instead see: https://discourse.oss.antheminc.com/
```

### Code Snippet

# Environment Details
* **Nimbus Version:**

* **Browser:**

**Comment by lopezton-anthem** [comment]
This issue was resolved with an application configuration change revolving around `@PageHeader(PageHeader.Property.LOGOUT)`

Documentation needs to be added to explain how `PageHeader` works. Linking the [Jira issue for that documentation update here](https://anthemopensource.atlassian.net/browse/NIMBUS-159).
