### ISSUE TITLE
Selected value in drop-down is not retained

### ISSUE THREAD

**Issue by saritabarve** [openanthem/nimbus-core#515]
Value selection in Dropdown – selected value is not retained.

Have to select multiple times to have the value retained in selection.

**Comment by addulaajayreddy** [comment]
We are still seeing this issue with combobox select @lopezton-anthem

**Comment by lopezton-anthem** [comment]
@andulaajayreddy Thanks for your issue request.

In order to address the issue you're facing, please provide the more details on how to recreate the issue. If you're unsure of which details to provide, we've provided a handy issue template [here](https://github.com/openanthem/nimbus-core/blob/master/.github/issue_template.md).

**Comment by lopezton-anthem** [comment]
I took a look with @addulaajayreddy, the issue comes due to data mismatch between the type of the field and the type of the `code` field in `ParamValue`.

The UI assumes that the state of `@ComboBox` will always be `String`,  but that is not the case.  Consider the following:

```java
@Values(url = "client/app/p/queue/_search?fn=lookup&orderby=queue.name.asc()&projection.mapsTo=code:id,label:name")
@ComboBox(postEventOnChange = true)
private Long id;
```

`ParamValue` assumes that `code` is of type `Object`, while `SearchFunctionHandlerLookup` assumes it needs to be converted to `String` for the UI. I see no reason why `String` needs to be assumed as `String` here. @sandeepmantha can we remove the `val?val.toString():val` change in `combobox.component.ts` and change `SearchFunctionHandlerLookup` to simply pass `code` as an `Object`?

**Comment by saritabarve** [comment]
++ Dileep, Chandra, Nanda

**Comment by lopezton-anthem** [comment]
Change was deployed to 1.3.0.M6

**Comment by addulaajayreddy** [comment]
This issue is happening in 1.3.1.M6 version again. Can some one please take a look?
