### ISSUE TITLE
Mandatory fields validation is skipped when completing fields non-sequentially

### ISSUE THREAD

**Issue by saritabarve** [openanthem/nimbus-core#529]
Mandatory fields validation is skipped when completing fields non-sequentially

**Comment by lopezton-anthem** [comment]
Thanks for your issue request.

In order to address the issue you're facing, please provide the more details on how to recreate the issue. If you're unsure of which details to provide, we've provided a handy issue template [here](https://github.com/openanthem/nimbus-core/blob/master/.github/issue_template.md).
