### ISSUE TITLE
Selected values are not retained in drop-downs

### ISSUE THREAD

**Issue by saritabarve** [openanthem/nimbus-core#550]
User owner are not retained and are blank. (In this scenario User owner should not be blank)

**Comment by lopezton-anthem** [comment]
Thanks for your issue request.

In order to address the issue you're facing, please provide the more details on how to recreate the issue. If you're unsure of which details to provide, we've provided a handy issue template [here](https://github.com/openanthem/nimbus-core/blob/master/.github/issue_template.md).

**Comment by lopezton-anthem** [comment]
I spoke with the team, and this would be resolved by fixing the issue correlated with #552.  This issue is then not needed.
