### ISSUE TITLE
BPMN not generating the next task in workflow

### ISSUE THREAD

**Issue by saritabarve** [openanthem/nimbus-core#551]
BPMN execution is not generating the next task in workflow. The `ProcessFlow` data retrieved from the session cache is not matching the value in the database for a particular process id, which is causing BPMN conditional checks to fail.

**Comment by lopezton-anthem** [comment]
Thanks for your issue request.

In order to address the issue you're facing, please provide the more details on how to recreate the issue. If you're unsure of which details to provide, we've provided a handy issue template [here](https://github.com/openanthem/nimbus-core/blob/master/.github/issue_template.md).

**Comment by lopezton-anthem** [comment]
I got with the team and saw the behavior. I've updated the issue details to reflect what we believe the issue to be. Need to review with @jayantchaudhuri

**Comment by lopezton-anthem** [comment]
After working with the teams, we found that the session id was being preserved incorrectly and used to retrieve an incorrect parameter from the session cache. The teams were able to resolve this by cleaning out that session between subsequent requests.
