### ISSUE TITLE
System generated multiple records, user unable to complete

### ISSUE THREAD

**Issue by saritabarve** [openanthem/nimbus-core#553]
System generated multiple records, user unable to complete

**Comment by lopezton-anthem** [comment]
Thanks for your issue request.

In order to address the issue you're facing, please provide the more details on how to recreate the issue. If you're unsure of which details to provide, we've provided a handy issue template [here](https://github.com/openanthem/nimbus-core/blob/master/.github/issue_template.md).

**Comment by lopezton-anthem** [comment]
I spoke with the team and reviewed this issue. This issue would be resolved by fixing the issue correlated with #531, making this issue a duplicate. This issue is then not needed and will be closed.
