### ISSUE TITLE
Create New User Roles in HIP

### ISSUE THREAD

**Issue by lalitshivnani** [openanthem/nimbus-core#554]
JIRA ID available in the email sent to Jamie. Please reach out to Biju Suresh for any details.
This feature is about configuring different user roles for applications and defining their authorities. The functionality of UI page access restriction based on roles is new to application and there is no framework component available for building this functionality. The solution cannot be implemented for each UI page , as it is not a scalable solution for future UI enhancements.

**Comment by lopezton-anthem** [comment]
Thanks for your issue request.

In order to address the issue you're facing, please provide the more details on how to recreate the issue. If you're unsure of which details to provide, we've provided a handy issue template [here](https://github.com/openanthem/nimbus-core/blob/master/.github/issue_template.md).

**Comment by lopezton-anthem** [comment]
I spoke with the team and was informed that they should be the ones to look into this. If necessary, please schedule time with one of the framework team members to help identify the possible root causes.
