### ISSUE TITLE
Grid sort not working on GridColumn that is not mapped to any variable in the backing object

### ISSUE THREAD

**Issue by af48078** [openanthem/nimbus-core#559]
# Issue Details

**Type of Issue**  (check one with "X")
```
[ ] Bug Report => Please search GitHub for a similar issue or PR before submitting
[ ] Feature Request => Please ensure feature is not already in progress
[ ] Support Request => Please do not submit support requests here, instead see: https://discourse.oss.antheminc.com/
```

## Current Behavior
Server Side Pagination is On and Sortable is enabled, When we try to sort the GridColumn that is unmapped it throws a ClassCastException

## Expected Behavior
Should be able to sort the values without error

### Steps to Reproduce
On-grid enable Server Side Pagination, declare a GridColumn without mapping it to any variable in the backing object and enable sortable, Click Sort on the Grid, Now It throws ClassCastException and Sorting doesn't happen

### Code Snippet
@GridColumn(sortable = true,sortAs=SortAs.NUMBER)
private Double penaltyDouble;

# Environment Details
* **Nimbus Version:**

* **Browser:**

**Comment by lopezton-anthem** [comment]
After discussing this with the team, we have asked that either an aggregate query or mongo view be created to support this scenario. Serverside pagination relies on sorting to be done in the database layer, which is why this is not supported.  If we have to support this by adding collection sorting support on the server, we'll revisit it in a new feature.
