### ISSUE TITLE
Asterisk for mandatory fields are not aligned

### ISSUE THREAD

**Issue by ramank21** [openanthem/nimbus-core#631]
# Issue Details

**Type of Issue**  (check one with "X")
```
[ ] Bug Report => Please search GitHub for a similar issue or PR before submitting
[ ] Feature Request => Please ensure feature is not already in progress
[ ] Support Request => Please do not submit support requests here, instead see: https://discourse.oss.antheminc.com/
```

### Code Snippet

# Environment Details
* **Nimbus Version:**

* **Browser:**

**Comment by lopezton-anthem** [comment]
Thanks for your issue request.

In order to address the issue you're facing, please provide the more details on how to recreate the issue. If you're unsure of which details to provide, we've provided a handy issue template [here](https://github.com/openanthem/nimbus-core/blob/master/.github/issue_template.md).

**Comment by sandeepmantha** [comment]
This seems to be an issue with chrome browser. If you are on version 78 series, it will work fine. If you are on either 77 or 76 you might see this issue.
